site_name: NOTAS DE HACKING DE ERIS
nav:
  - Inicio:
    - 'Bienvenidos': 'es/index.md'
    - RUTAS DE ESTUDIO:
      - 'eJPT': 'es/ejpt.md'
      - 'OSCP': 'es/oscp.md'
      - 'CPTS': 'es/cpts.md'
  - 'Redes':
    - 'Introducción a las redes': 'es/redes.md'
  - 'Enumeración de Servicios':
    - 'Introducción a la enumeración': 'es/enumeration.md'
    - 'SERVICIOS':
      - 'Enumeración FTP': 'es/ftp-enum.md'
      - 'Enumeración SMB': 'es/smb-enum.md'
      - 'Enumeración NFS': 'es/nfs-enum.md'
      - 'Enumeración DNS': 'es/dns-enum.md'
      - 'Enumeración SMTP': 'es/smtp-enum.md'
      - 'Enumeración IMAP/POP3': 'es/imap-pop3-enum.md'
      - 'Enumeración SNMP': 'es/snmp-enum.md'
      - 'Enumeración MySQL': 'es/mysql-enum.md'
      - 'Enumeración MSSQL': 'es/mssql-enum.md'
      - 'Enumeración Oracle TNS': 'es/oracle-tns-enum.md'
      - 'Enumeración IPMI': 'es/ipmi-enum.md'

  - 'Open-Source Intelligence (OSINT)':
    - 'Introducción al OSINT': 'es/osint.md'
    - 'Sock Puppets': 'es/sock-puppets.md'
    - 'OSINT DE IMAGENES':
      - 'Ver datos de EXIF': 'es/exif-osint.md'
    - 'OSINT DE REDES SOCIALES':
      - 'Facebook': 'es/facebook-osint.md'
      - 'Instagram': 'es/instagram-osint.md'
      - 'LinkedIn': 'es/linkedin-osint.md'
      - 'Reddit': 'es/reddit-osint.md'
      - 'Snapchat': 'es/snapchat-osint.md'
      - 'TikTok': 'es/tiktok-osint.md'
      - 'Twitter': 'es/twitter-osint.md'
  - 'Hacking Web':
    - 'GENERAL':
      - 'Introducción': 'es/hacking-web.md'
      - 'Protocolo HTTP': 'es/http.md'
    - 'FUZZING':
      - 'Introducción al fuzzing': 'es/fuzzing.md'
      - 'Fuzzing de directorios': 'es/directory-fuzzing.md'
      - 'Fuzzing de extensiones de archivos': 'es/file-extension-fuzzing.md'
      - 'Fuzzing de parámetros': 'es/parameter-fuzzing.md'
      - 'Fuzzing de subdominios': 'es/subdomain-fuzzing.md'
      - 'Fuzzing de vhosts': 'es/vhost-fuzzing.md'
    - 'WEB PROXIES':
      - 'Introducción a los proxies web': 'es/web-proxies.md'
      - 'Burp Suite': 'es/burp-suite.md'
      - 'Zed Attack Proxie (ZAP)': 'es/zap.md'
    - 'CROSS-SITE SCRIPTING (XSS)':
      - 'Introducción al XSS': 'es/xss.md'
      - 'XSS Reflejado': 'es/reflected-xss.md'
      - 'XSS Almacenado': 'es/stored-xss.md'
      - 'XSS DOM': 'es/dom-xss.md' 
  - 'Active Directory':
    - 'Introducción al Active Directory (AD)': 'es/active-directory.md'
  - 'Escalada de privilegios':
    - 'Introducción a la escalada de privilegios': 'es/privilege-escalation.md'
    - 'WINDOWS':
      - 'Dnsadmins': 'es/dnsadmins-windows.md'
    - 'LINUX':
      - 'Abuso del PATH': 'es/path-abuse-linux.md'
  - 'Reportes y documentación': 
    - 'Introducción a los reportes y documentación': 'es/reporting.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: Español
      link: /es/
      lang: es

  social:
    - icon: fontawesome/brands/github-alt
      link: http://github.com/eris-os
    - icon: fontawesome/brands/discord
      link: http://discord.gg/eris-os
    - icon: fontawesome/brands/linkedin
      link: http://linkedin.com/in/eris-os
    - icon: fontawesome/brands/youtube
      link: http://youtube.com/eris-os

copyright: |
  &copy; 2025 <a href="https://github.com/eris-os" target="_blank" rel="noopener">Eris Ortega</a>